// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetFamily.VolunteerRequest.Infrastructure;

#nullable disable

namespace PetFamily.VolunteerRequest.Infrastructure.Migrations
{
    [DbContext(typeof(VolunteerRequestWriteDbContext))]
    [Migration("20241105102301_VolunteerRequest_Initial")]
    partial class VolunteerRequest_Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("volunteer_requests")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetFamily.VolunteerRequest.Domain.UserRestriction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("BannedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("banned_until");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ComplexProperty<Dictionary<string, object>>("Reason", "PetFamily.VolunteerRequest.Domain.UserRestriction.Reason#RejectionDescription", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("reason_description");
                        });

                    b.HasKey("Id")
                        .HasName("pk_user_restrictions");

                    b.ToTable("user_restrictions", "volunteer_requests");
                });

            modelBuilder.Entity("PetFamily.VolunteerRequest.Domain.VolunteerRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DiscussionId")
                        .HasColumnType("uuid")
                        .HasColumnName("discussion_id");

                    b.Property<Guid>("InspectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("inspector_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_volunteer_requests");

                    b.ToTable("volunteer_requests", "volunteer_requests");
                });

            modelBuilder.Entity("PetFamily.VolunteerRequest.Domain.VolunteerRequest", b =>
                {
                    b.OwnsOne("PetFamily.VolunteerRequest.Domain.ValueObjects.RejectionDescription", "RejectionDescription", b1 =>
                        {
                            b1.Property<Guid>("VolunteerRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("rejection_description");

                            b1.HasKey("VolunteerRequestId");

                            b1.ToTable("volunteer_requests", "volunteer_requests");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerRequestId")
                                .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                        });

                    b.OwnsOne("PetFamily.VolunteerRequest.Domain.ValueObjects.VolunteerInformation", "Information", b1 =>
                        {
                            b1.Property<Guid>("VolunteerRequestId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Requisites")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("requisites");

                            b1.HasKey("VolunteerRequestId");

                            b1.ToTable("volunteer_requests", "volunteer_requests");

                            b1.WithOwner()
                                .HasForeignKey("VolunteerRequestId")
                                .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");

                            b1.OwnsOne("PetFamily.SharedKernel.ValueObjects.AgeExperience", "AgeExperience", b2 =>
                                {
                                    b2.Property<Guid>("VolunteerInformationVolunteerRequestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<int>("Years")
                                        .HasColumnType("integer")
                                        .HasColumnName("years");

                                    b2.HasKey("VolunteerInformationVolunteerRequestId");

                                    b2.ToTable("volunteer_requests", "volunteer_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("VolunteerInformationVolunteerRequestId")
                                        .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                                });

                            b1.OwnsOne("PetFamily.SharedKernel.ValueObjects.Description", "Description", b2 =>
                                {
                                    b2.Property<Guid>("VolunteerInformationVolunteerRequestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(2000)
                                        .HasColumnType("character varying(2000)")
                                        .HasColumnName("volunteer_description");

                                    b2.HasKey("VolunteerInformationVolunteerRequestId");

                                    b2.ToTable("volunteer_requests", "volunteer_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("VolunteerInformationVolunteerRequestId")
                                        .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                                });

                            b1.OwnsOne("PetFamily.SharedKernel.ValueObjects.FullName", "FullName", b2 =>
                                {
                                    b2.Property<Guid>("VolunteerInformationVolunteerRequestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("name");

                                    b2.Property<string>("Patronymic")
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("patronymic");

                                    b2.Property<string>("Surname")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("surname");

                                    b2.HasKey("VolunteerInformationVolunteerRequestId");

                                    b2.ToTable("volunteer_requests", "volunteer_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("VolunteerInformationVolunteerRequestId")
                                        .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                                });

                            b1.OwnsOne("PetFamily.SharedKernel.ValueObjects.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("VolunteerInformationVolunteerRequestId")
                                        .HasColumnType("uuid")
                                        .HasColumnName("id");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("number");

                                    b2.HasKey("VolunteerInformationVolunteerRequestId");

                                    b2.ToTable("volunteer_requests", "volunteer_requests");

                                    b2.WithOwner()
                                        .HasForeignKey("VolunteerInformationVolunteerRequestId")
                                        .HasConstraintName("fk_volunteer_requests_volunteer_requests_id");
                                });

                            b1.Navigation("AgeExperience")
                                .IsRequired();

                            b1.Navigation("Description")
                                .IsRequired();

                            b1.Navigation("FullName")
                                .IsRequired();

                            b1.Navigation("PhoneNumber")
                                .IsRequired();
                        });

                    b.Navigation("Information")
                        .IsRequired();

                    b.Navigation("RejectionDescription");
                });
#pragma warning restore 612, 618
        }
    }
}
